"""
dependency_engine.py

Determines the next action in a HealthOS workflow.

This module is the central dependency controller.

It decides whether the system should:

1. Ask the user for information (ASK_USER)
2. Run a system-generated dependency (RUN_SYSTEM)
3. Mark the task as complete (COMPLETE)
4. Handle an emergency workflow (EMERGENCY)
5. Wait if prerequisites are not yet met (WAIT)

IMPORTANT:
This module:
- Does NOT call the LLM
- Does NOT extract information
- Does NOT generate responses

It only decides what happens next based on the dynamic state schema.
"""

from typing import Any, Dict, List, Optional

try:
    from task_definitions import (
        TASK_DEPENDENCIES,
        DERIVED_DEPENDENCIES,
        Task,
    )
    from state_schema import (
        is_dependency_satisfied,
    )
except ImportError:
    from agents.task_definitions import (
        TASK_DEPENDENCIES,
        DERIVED_DEPENDENCIES,
        Task,
    )
    from agents.state_schema import (
        is_dependency_satisfied,
    )


class DependencyEngine:


    def get_next_action(
        self,
        schema: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Determine what should happen next.

        Returns:
        {
            "action": str,           # "ASK_USER" | "RUN_SYSTEM" | "COMPLETE" | "EMERGENCY" | "WAIT"
            "dependency": str | None,
            "message_type": str | None,
            # If RUN_SYSTEM:
            # "generator": str,
            # "depends_on": list
        }
        """

        task = schema.get("task")

        if not task:
            return {
                "action": "WAIT",
                "dependency": None,
                "message_type": "task_not_resolved",
            }

        if task == Task.EMERGENCY.value:
            return {
                "action": "EMERGENCY",
                "dependency": None,
                "message_type": "emergency",
            }

        dependencies = TASK_DEPENDENCIES.get(
            task,
            [],
        )

        for dependency in dependencies:
            if not is_dependency_satisfied(
                schema,
                dependency,
            ):
                return self._handle_missing_dependency(
                    task=task,
                    dependency=dependency,
                    schema=schema,
                )

        return {
            "action": "COMPLETE",
            "dependency": None,
            "message_type": "task_complete",
        }


    def _handle_missing_dependency(
        self,
        task: str,
        dependency: str,
        schema: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Determine whether the missing dependency should be:
        - Collected from the user (ASK_USER)
        - Generated by the system (RUN_SYSTEM)
        """

        derived_dependencies = DERIVED_DEPENDENCIES.get(
            task,
            {},
        )

        dependency_config = derived_dependencies.get(dependency)

        if dependency_config:
            required_inputs = dependency_config.get(
                "depends_on",
                [],
            )

            if schema is not None:
                inputs_ready = all(
                    is_dependency_satisfied(
                        schema,
                        required_input,
                    )
                    for required_input in required_inputs
                )

                if not inputs_ready:
                    return {
                        "action": "WAIT",
                        "dependency": dependency,
                        "message_type": "system_inputs_missing",
                    }

            return {
                "action": "RUN_SYSTEM",
                "dependency": dependency,
                "generator": dependency_config.get("generated_by"),
                "depends_on": required_inputs,
                "message_type": "system_dependency",
            }

        return {
            "action": "ASK_USER",
            "dependency": dependency,
            "message_type": "user_dependency",
        }


    def update_schema_state(
        self,
        schema: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Updates:
        - current_dependency
        - stage

        based on the next required action.
        """

        result = self.get_next_action(schema)
        action = result.get("action")
        dependency = result.get("dependency")

        if action == "ASK_USER":
            schema["current_dependency"] = dependency
            schema["stage"] = f"collecting_{dependency}"

        elif action == "RUN_SYSTEM":
            schema["current_dependency"] = dependency
            schema["stage"] = f"generating_{dependency}"

        elif action == "COMPLETE":
            schema["current_dependency"] = None
            schema["stage"] = "ready"

        elif action == "EMERGENCY":
            schema["current_dependency"] = None
            schema["stage"] = "emergency"

        return schema


    def get_missing_dependencies(
        self,
        schema: Dict[str, Any],
    ) -> List[str]:
        """
        Return all currently missing dependencies.
        Useful for debugging and testing.
        """

        task = schema.get("task")

        if not task:
            return []

        dependencies = TASK_DEPENDENCIES.get(
            task,
            [],
        )

        missing = []

        for dependency in dependencies:
            if not is_dependency_satisfied(
                schema,
                dependency,
            ):
                missing.append(dependency)

        return missing
